# Depth to LaserScan Parameters
depthimage_to_laserscan:
  ros__parameters:
    # Output frame for the laser scan
    output_frame_id: "camera_depth_frame"
    
    # Range limits
    range_min: 0.1          # Minimum range in meters
    range_max: 10.0         # Maximum range in meters
    
    # Scan parameters
    scan_height: 10         # Number of pixel rows to use for scan (increase for more coverage)
    scan_time: 0.033        # Time between scans (30 Hz)
    
    # Angular parameters  
    angle_min: -1.5708      # -90 degrees in radians
    angle_max: 1.5708       # +90 degrees in radians
    angle_increment: 0.00436 # Angular resolution (0.25 degrees)
    
    # Image processing
    use_inf: true           # Use infinity for max range
    inf_epsilon: 1.0        # Epsilon for infinity comparison
